options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/$PROJECT_ID/polygon-mcp/polygon-mcp:latest
      - -f
      - Dockerfile
      - .

images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/polygon-mcp/polygon-mcp:latest
